name: Compare config to GTFS (reported via GitHub issue)

on:
  schedule:
    # 8am AEST (9am AEDT) every Saturday
    - cron: "0 22 * * 5"
    # 5pm AEST (6pm AEDT) every Tuesday
    - cron: "0 7 * * 2"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  compare-and-report:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.14.0
      - run: npm ci
      - name: Run comparison and report
        run: npm run compare-config-to-gtfs -- --create-github-issue
        env:
          RELAY_KEY: ${{ secrets.RELAY_KEY }}
          GITHUB_API_URL: ${{ github.api_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          COMMIT_SHA: ${{ github.sha }}
